# --- Defaults for 4x4 predator prey, 4 agent capture, walls ---

env: "dec_tiger_full"
env_args:
    n_agents: 2
    map_name: dec_tiger_full
    failure_obs_prob: 0.0
    fully_observable: True
gamma: 1.0
t_max: 1000000
test_nepisode: 16 # Number of episodes to test for
test_interval: 10000